<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#数据探索" data-toc-modified-id="数据探索-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>数据探索</a></span></li><li><span><a href="#缺失值处理" data-toc-modified-id="缺失值处理-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>缺失值处理</a></span></li><li><span><a href="#描述性统计与数据预处理" data-toc-modified-id="描述性统计与数据预处理-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>描述性统计与数据预处理</a></span><ul class="toc-item"><li><span><a href="#有多少球队参与了2012欧洲杯？" data-toc-modified-id="有多少球队参与了2012欧洲杯？-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>有多少球队参与了2012欧洲杯？</a></span></li><li><span><a href="#将数据集中的列Team,-Yellow-Cards和Red-Cards单独存为一个名叫discipline的数据框" data-toc-modified-id="将数据集中的列Team,-Yellow-Cards和Red-Cards单独存为一个名叫discipline的数据框-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>将数据集中的列Team, Yellow Cards和Red Cards单独存为一个名叫discipline的数据框</a></span></li><li><span><a href="#对数据框discipline按照先Red-Cards再Yellow-Cards进行降序排序" data-toc-modified-id="对数据框discipline按照先Red-Cards再Yellow-Cards进行降序排序-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>对数据框discipline按照先Red Cards再Yellow Cards进行降序排序</a></span></li><li><span><a href="#计算每个球队拿到的黄牌数的平均值" data-toc-modified-id="计算每个球队拿到的黄牌数的平均值-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>计算每个球队拿到的黄牌数的平均值</a></span></li><li><span><a href="#找到进球数Goals超过6的球队数据" data-toc-modified-id="找到进球数Goals超过6的球队数据-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>找到进球数Goals超过6的球队数据</a></span></li><li><span><a href="#对比英格兰(England)、意大利(Italy)和俄罗斯(Russia)的射正率(Shooting-Accuracy)" data-toc-modified-id="对比英格兰(England)、意大利(Italy)和俄罗斯(Russia)的射正率(Shooting-Accuracy)-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>对比英格兰(England)、意大利(Italy)和俄罗斯(Russia)的射正率(Shooting Accuracy)</a></span></li></ul></li></ul></div>

In [1]:
import numpy as np,pandas as pd

In [3]:
eu = pd.read_csv("Euro2012_stats.csv")
eu.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

# 数据探索

In [4]:
eu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 35 columns):
Team                          16 non-null object
Goals                         16 non-null int64
Shots on target               16 non-null int64
Shots off target              16 non-null int64
Shooting Accuracy             16 non-null object
% Goals-to-shots              16 non-null object
Total shots (inc. Blocked)    16 non-null int64
Hit Woodwork                  16 non-null int64
Penalty goals                 16 non-null int64
Penalties not scored          16 non-null int64
Headed goals                  16 non-null int64
Passes                        16 non-null int64
Passes completed              16 non-null int64
Passing Accuracy              16 non-null object
Touches                       16 non-null int64
Crosses                       16 non-null int64
Dribbles                      16 non-null int64
Corners Taken                 16 non-null int64
Tackles                       16 non-null int64
Clearances                    16 non-null int64
Interceptions                 16 non-null int64
Clearances off line           15 non-null float64
Clean Sheets                  16 non-null int64
Blocks                        16 non-null int64
Goals conceded                16 non-null int64
Saves made                    16 non-null int64
Saves-to-shots ratio          16 non-null object
Fouls Won                     16 non-null int64
Fouls Conceded                16 non-null int64
Offsides                      16 non-null int64
Yellow Cards                  16 non-null int64
Red Cards                     16 non-null int64
Subs on                       16 non-null int64
Subs off                      16 non-null int64
Players Used                  16 non-null int64
dtypes: float64(1), int64(29), object(5)
memory usage: 4.5+ KB

```

   
    
   
   
```

# 缺失值处理

In [7]:
eu["Clearances off line"]
eu["Clearances off line"].fillna(value=0)

0     0.0
1     2.0
2     0.0
3     1.0
4     0.0
5     0.0
6     0.0
7     1.0
8     0.0
9     0.0
10    0.0
11    1.0
12    0.0
13    0.0
14    0.0
15    0.0
Name: Clearances off line, dtype: float64

```

   
    
   
   
```

# 描述性统计与数据预处理

## 有多少球队参与了2012欧洲杯？

In [8]:
len(eu)

16

```
 
   
   
```
## 将数据集中的列Team, Yellow Cards和Red Cards单独存为一个名叫discipline的数据框

In [19]:
discipline=eu[["Team","Yellow Cards","Red Cards"]]
discipline

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

```
 
   
   
```
## 对数据框discipline按照先Red Cards再Yellow Cards进行降序排序

In [20]:
discipline.sort_values(by=["Red Cards","Yellow Cards"],ascending=False)

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
0               Croatia             9          0
1        Czech Republic             7          0
14               Sweden             7          0
4                France             6          0
12               Russia             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
2               Denmark             4          0
5               Germany             4          0

```
 
   
   
```
## 计算每个球队拿到的黄牌数的平均值

In [26]:
discipline["Yellow Cards"].mean()

7.4375

```
 
   
   
```
## 找到进球数Goals超过6的球队数据

In [35]:
eu.assign(Goal=eu["Goals"].astype(int))
eu[eu.Goals>6]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18

```
 
   
   
```

## 对比英格兰(England)、意大利(Italy)和俄罗斯(Russia)的射正率(Shooting Accuracy)

In [87]:
T=["England","Italy","Russia"]
index = pd.Index(eu[["Team","Shooting Accuracy"]].iloc[:,0],name="球队名")
a=eu[["Team","Shooting Accuracy"]]
a.index=index
a=a.drop(columns="Team")
a.loc[["England","Italy","Russia"]]

        Shooting Accuracy
球队名
England             50.0%
Italy               43.0%
Russia              22.5%

In [47]:
##  综合题
- euro12中有哪些字段属于object类?
- 提取带百分号字符的字段到一个新的DataFrame中
- 在新DataFrame中，将带有百分号的字符转化为浮点型数据
- 在上表所有列标签中后面备注——（%）

SyntaxError: invalid character in identifier (<ipython-input-47-f0e392d677cb>, line 4)

In [154]:
eu.describe(include=["object"])

,Team,Shooting Accuracy,% Goals-to-shots,Passing Accuracy,Saves-to-shots ratio
count,16,16,16,16,16
unique,16,15,14,15,15
top,Portugal,50.0%,16.0%,83.9%,66.7%
freq,1,2,2,2,2

In [191]:
title=eu.describe(include=["object"]).iloc[:,1:].columns.tolist()
eu1=eu[title]
eu1

   Shooting Accuracy % Goals-to-shots Passing Accuracy Saves-to-shots ratio
0              51.9%            16.0%            76.9%                81.3%
1              41.9%            12.9%            78.1%                60.1%
2              50.0%            20.0%            83.3%                66.7%
3              50.0%            17.2%            80.6%                88.1%
4              37.9%             6.5%            87.2%                54.6%
5              47.8%            15.6%            87.4%                62.6%
6              30.7%            19.2%            76.7%                65.1%
7              43.0%             7.5%            83.9%                74.1%
8              25.0%             4.1%            88.7%                70.6%
9              39.4%             5.2%            80.4%                66.7%
10             34.3%             9.3%            77.2%                71.5%
11             36.8%             5.2%            71.2%                65.4%
12             22.5%            12.5%            83.9%                77.0%
13             55.9%            16.0%            88.4%                93.8%
14             47.2%            13.8%            80.9%                61.6%
15             21.2%             6.0%            81.7%                76.5%

In [192]:
eu1
def tran(x):
    return float(x[:-1])/100

eu1.applymap(tran)

,Shooting Accuracy,% Goals-to-shots,Passing Accuracy,Saves-to-shots ratio
0,0.519,0.160,0.769,0.813
1,0.419,0.129,0.781,0.601
2,0.500,0.200,0.833,0.667
3,0.500,0.172,0.806,0.881
4,0.379,0.065,0.872,0.546
5,0.478,0.156,0.874,0.626
6,0.307,0.192,0.767,0.651
7,0.430,0.075,0.839,0.741
8,0.250,0.041,0.887,0.706
9,0.394,0.052,0.804,0.667
10,0.343,0.093,0.772,0.715
11,0.368,0.052,0.712,0.654
12,0.225,0.125,0.839,0.770
13,0.559,0.160,0.884,0.938
14,0.472,0.138,0.809,0.616
15,0.212,0.060,0.817,0.765

In [200]:
title[1] = "Goals-to-shots"
eu1.columns=title

In [201]:
def add(x):
    return x + r"(%)"

eu1.columns=eu1.columns.map(add)
eu1

,Shooting Accuracy(%),Goals-to-shots(%),Passing Accuracy(%),Saves-to-shots ratio(%)
0,51.9%,16.0%,76.9%,81.3%
1,41.9%,12.9%,78.1%,60.1%
2,50.0%,20.0%,83.3%,66.7%
3,50.0%,17.2%,80.6%,88.1%
4,37.9%,6.5%,87.2%,54.6%
5,47.8%,15.6%,87.4%,62.6%
6,30.7%,19.2%,76.7%,65.1%
7,43.0%,7.5%,83.9%,74.1%
8,25.0%,4.1%,88.7%,70.6%
9,39.4%,5.2%,80.4%,66.7%
10,34.3%,9.3%,77.2%,71.5%
11,36.8%,5.2%,71.2%,65.4%
12,22.5%,12.5%,83.9%,77.0%
13,55.9%,16.0%,88.4%,93.8%
14,47.2%,13.8%,80.9%,61.6%
15,21.2%,6.0%,81.7%,76.5%